(() => {
 const dialog=document.getElementById('reader-paper-cards');if(!dialog)return;
 const C=PaperCards,input=dialog.querySelector('input'),view=dialog.querySelector('[data-card-view]'),results=dialog.querySelector('.reader-card-results'),status=dialog.querySelector('.reader-card-status'),full=dialog.querySelector('.reader-card-full'),browser=dialog.querySelector('.reader-card-browser'),preview=dialog.querySelector('.reader-card-preview'),body=dialog.querySelector('.reader-card-content');
 let type='',serial=0,reading=0,data,search,selected,active,limit=30,opener;
 const filters=()=>({q:input.value.trim(),view:view.value,type});
 async function render(){const ticket=++serial;status.textContent='Loading paper cards…';try{if(!data){data=await C.index();const old=view.value;view.innerHTML=C.options(data.papers);view.value=old||'ai';}if(input.value.trim()&&!search)search=await C.vocabulary();if(ticket!==serial)return;const f=filters(),matches=data.papers.filter(p=>C.matches(p,f,search));full.href=C.galleryURL(f);status.textContent=matches.length.toLocaleString()+' matching '+(matches.length===1?'paper':'papers')+(matches.length>limit?' · first '+limit+' shown':'');results.innerHTML=matches.slice(0,limit).map(p=>C.tile(p,selected?.id)).join('')||'<p>No papers match these filters.</p>';dialog.querySelector('[data-more-cards]').hidden=matches.length<=limit;}catch{if(ticket===serial)status.textContent='Cards could not be loaded. Open the gallery below.';}}
 async function open(p,id){selected=p;active=p.cards.find(c=>c.id===id)||p.cards.find(c=>!type||c.type===type)||p.cards[0];const card=active,ticket=++reading;results.querySelectorAll('[data-paper]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.paper===p.id)));browser.hidden=true;preview.hidden=false;body.innerHTML='<p role="status">Loading card…</p>';dialog.querySelector('.reader-card-gallery-link').href=C.galleryURL(filters(),card);dialog.scrollTop=0;dialog.querySelector('[data-back-cards]').focus({preventScroll:true});try{const c=await C.detail(card);if(ticket!==reading)return;body.innerHTML=C.renderCard(p,card,c,'reader-card');}catch{if(ticket===reading)body.innerHTML='<p role="status">Could not load this card. Open it in the gallery or return to the results.</p>';}}
 function back(){++reading;preview.hidden=true;browser.hidden=false;dialog.scrollTop=0;const tile=[...results.querySelectorAll('[data-paper]')].find(b=>b.dataset.paper===selected?.id);(tile||input).focus({preventScroll:true});}
 results.addEventListener('click',e=>{const b=e.target.closest('[data-paper]');if(b)open(data.papers.find(p=>p.id===b.dataset.paper));});
 body.addEventListener('click',e=>{if(e.target.closest('.card-measurement-guide a')){opener=null;dialog.close();return;}const b=e.target.closest('[data-card]');if(b)open(selected,b.dataset.card);C.sectionClick(e,body);});
 dialog.querySelector('[data-back-cards]').addEventListener('click',back);
 document.querySelectorAll('[data-open-paper-cards]').forEach(b=>b.addEventListener('click',()=>{opener=b;dialog.showModal();if(preview.hidden){render();input.focus();}else dialog.querySelector('[data-back-cards]').focus();}));
 dialog.querySelector('[data-close-paper-cards]').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());
 dialog.querySelectorAll('[data-card-gallery]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.cardGallery==='all'?'':b.dataset.cardGallery;dialog.querySelectorAll('[data-card-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));limit=30;render();}));
 view.addEventListener('change',()=>{limit=30;render();});dialog.querySelector('[data-more-cards]').addEventListener('click',()=>{limit+=30;render();});
 let timer;input.addEventListener('input',()=>{++serial;clearTimeout(timer);timer=setTimeout(()=>{limit=30;render();},150);});
})();
